version: "3.8"

services:
  frontend:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src #Observa alguma mudança no ./front/src e joga caso tenha para o /app/src

  backend:
    build: ./Back/test-back
    ports:
      - 5000:5000
